In [147]:
import torch

In [148]:
scaler = torch.tensor(10)
scaler

tensor(10)

In [149]:
scaler.dtype

torch.int64

In [150]:
scaler.dim()

0

In [151]:
vect = torch.tensor([1,2,3,4,5])
vect

tensor([1, 2, 3, 4, 5])

In [152]:
vect.shape

torch.Size([5])

In [153]:
vect.dim()

1

In [154]:
matrix = torch.tensor([[1,2] , [3,4] , [5,6]])
matrix

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [155]:
matrix.shape

torch.Size([3, 2])

In [156]:
matrix.dim()

2

In [157]:
A = torch.rand((3,4))
A

tensor([[0.7916, 0.5478, 0.9297, 0.4623],
        [0.6253, 0.9954, 0.7434, 0.7576],
        [0.2167, 0.0627, 0.7019, 0.6594]])

In [158]:
Tensor = torch.arange(1,13,1)
Tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [159]:
Tensor = Tensor.reshape(3,4)
Tensor

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [160]:
Tensor[0,2]

tensor(3)

In [161]:
Tensor[: , 0:2]

tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]])

In [162]:
Tensor = torch.zeros((3,4))
Tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [163]:
Tensor = torch.ones((8,2))
Tensor

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [164]:
Tensor = torch.zeros_like(input=A)
Tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [165]:
Tensor = torch.ones_like(input=A)
Tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [166]:
Tensor = Tensor * 4
Tensor

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [167]:
Tns = torch.tensor([1,2,3,4,5,6,7,8])

In [168]:
Tns.view(Tns.shape[0] , 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])

In [169]:
Tns.reshape(-1 , 2)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [170]:
Tns = Tns.view(2 , 4)
Tns

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [171]:
Tensor = Tensor.reshape(4,3)
Tensor

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])

In [172]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

In [173]:
c = torch.multiply(a, b)
c

tensor([[ 5, 12],
        [21, 32]])

In [174]:
Tensor

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])

In [175]:
Tensor = Tensor.T
Tensor

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [176]:
Tensor.dtype

torch.float32

In [177]:
A = torch.rand(2,4 ,dtype=torch.float32)
B = torch.rand(4,5 ,dtype=torch.float32)

In [178]:
A @ B

tensor([[0.6785, 0.5033, 0.8051, 0.8019, 0.9648],
        [0.8565, 0.8162, 0.8822, 0.8329, 1.0925]])

In [179]:
torch.matmul(A , B)

tensor([[0.6785, 0.5033, 0.8051, 0.8019, 0.9648],
        [0.8565, 0.8162, 0.8822, 0.8329, 1.0925]])

In [180]:
a = torch.randint(low=0, high=10, size=(4,4), dtype=torch.int32)
b = torch.randint(low=0, high=10, size=(4,4), dtype=torch.int32)

In [181]:
(a.T + b.T) == (a + b).T

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [182]:
(a.T * a) == (a * a.T).T

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [183]:
a == (a.T).T

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [184]:
Tensor

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [185]:
Tensor = torch.add(Tensor , 3.5)
Tensor

tensor([[7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000]])

In [186]:
Tensor.add_(2)

tensor([[9.5000, 9.5000, 9.5000, 9.5000],
        [9.5000, 9.5000, 9.5000, 9.5000],
        [9.5000, 9.5000, 9.5000, 9.5000]])

In [187]:
torch.t(Tensor) == Tensor.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])

In [188]:
a = torch.arange(1,20,2)
a

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [189]:
torch.argmax(a)

tensor(9)

In [190]:
torch.argmin(a)

tensor(0)

In [191]:
torch.stack([a , a , a])

tensor([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])

In [198]:
a = a.reshape(2,5)
a

tensor([[ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19]])

In [199]:
a = a.permute(1 , 0)
a

tensor([[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]])